### ISSUE TITLE
录屏 截图 回调没有执行

### ISSUE THREAD

**Issue by desire0420** [rhymelph/r_forbidshot#1]
/// [captureWidget] 录屏时展示的Widget
/// [onCapture] 录屏时的回调
/// [onScreenShot] 截图时的回调

这三个回调没有执行是什么原因呀

**Comment by rhymelph** [comment]
有开start 吗?

**Comment by desire0420** [comment]
开了的  ，已经提示不能截屏了，但是就是没有回调

**Comment by rhymelph** [comment]
android 是没有回调的, 只能通过系统去处理, ios 会进行回调
